---
pipeline:
  build:
    privileged: true
    image: rancher/dapper:1.11.2
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    commands:
    - dapper ci

  stage-binaries:
    image: rancher/dapper:1.11.2
    commands:
    - cp -r ./bin/* ./package/
    when:
      branch: master
      event: tag

 
  github_binary_release:
    image: plugins/github-release
    files: bin/*
    secrets: [github_token]
    when:
      branch: master
      event: tag

  publish:
    image: plugins/docker
    dockerfile: package/Dockerfile
    repo: cloudnautique/ci-cdtesting
    context: package/
    tag: ${DRONE_TAG}
    secrets: [docker_username, docker_password]
    when:
      branch: master
      event: tag
